name: Run AddressSanitizer

on:
  push:

jobs:
  run-asan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: cfb125575a4c3a323998029fb148396eb1aac697
          
      - name: Install dependencies and build repository 
        run: | 
          sudo apt-get update
          sudo apt-get install -y libtool-* meson nasm numa-* libass-dev libass9 yasm pkg-config intltool libbluray2 libbluray-dev libdvdread-* libdvdnav-* libmp3lame-dev libmp3lame0 libopus-dev libopus0 libsamplerate0 libsamplerate0-dev libtheora-dev libtheora0 libvorbis0a libvorbisenc2 libvorbis-dev libvorbisfile3 libvorbisidec-dev libvorbisidec1 libvpx-dev libvpx7 libx264-* libx265-* libxml2 libxml2-dev zlib1g zlib1g-dev
      
      - name: Build repository 
        continue-on-error: true
        run: | 
          set +e
          export CC=clang
          export CXX=clang++
          export CFLAGS="-fsanitize=address -O1 -fno-omit-frame-pointer -fno-common -fsanitize-recover=address -g"
          export LDFLAGS="-fsanitize=address"
          ./configure --disable-gtk --launch-jobs=0 --launch

      - name: Install Address Sanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      
      - name: Run Google Address Sanitizer
        run: |
          set +e

          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_asan() {
            local executable="$1"
            ASAN_OPTIONS="check_initialization_order=true detect_stack_usr_after_return=true print_stats=true atexit=true strict_string_checks=true usr_odr_indicator=true verbosity=2" timeout 10s "$executable"
            local exit_status=$?
          }

          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_asan "$file"
            fi
          done
