name: Run Dr. Memory

on:
  push:

jobs:
  run-drmemory:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 
        with:
          ref: cfb125575a4c3a323998029fb148396eb1aac697

      - name: Install dependencies and build repository 
        run: | 
          sudo apt-get update
          sudo apt-get install -y libtool-* meson nasm numa-* libass-dev libass9 yasm pkg-config intltool libbluray2 libbluray-dev libdvdread-* libdvdnav-* libmp3lame-dev libmp3lame0 libopus-dev libopus0 libsamplerate0 libsamplerate0-dev libtheora-dev libtheora0 libvorbis0a libvorbisenc2 libvorbis-dev libvorbisfile3 libvorbisidec-dev libvorbisidec1 libvpx-dev libvpx7 libx264-* libx265-* libxml2 libxml2-dev zlib1g zlib1g-dev
          
      - name: Build repository 
        run: | 
          set +e
          export CC=gcc && export CXX=g++ && export CFLAGS="-g -fno-inline -fno-omit-frame-pointer" && export LDFLAGS=""
          ./configure --disable-gtk --launch-jobs=0 --launch
        continue-on-error: true 

      - name: Install Dr. Memory
        if: runner.os == 'Linux'
        run: | 
          sudo apt-get update
          sudo apt-get install -y libunwind8
          wget -P /tmp/ https://github.com/DynamoRIO/drmemory/releases/download/release_2.6.0/DrMemory-Linux-2.6.0.tar.gz && tar -xzf /tmp/DrMemory-Linux-2.6.0.tar.gz -C /tmp/ && echo "/tmp/DrMemory-Linux-2.6.0/bin" >> $GITHUB_PATH
           
      - name: Disable Address Space Randomization
        if: runner.os == 'Linux'
        run: sudo sysctl -w kernel.randomize_va_space=0
      
      - name: Disable swapping 
        if: runner.os == 'Linux' 
        run: sudo swapoff -a
        
      - name: Run Dr. Memory
        run: |
          #!/bin/bash
          mkdir -p drmem_logs
          set +e 

          echo "=========[Dr Memory Service Started!]========="

          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_drmemory() {
            local executable="$1"
            local log_dir="./logs"
            timeout 30s drmemory -logdir "./logs" -- "$executable"
            local exit_status=$?
          }

          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_drmemory "$file"
              echo ""
              echo ""
              echo ""
            fi
          done

          echo "=========[Dr. Memory service finished]========="

      - name: Upload Dr. Memory reports
        uses: actions/upload-artifact@v4
        with:
          name: drmemory-report-${{ github.event.repository.name }}-on-${{ matrix.os }}-from_branch_${{ github.ref_name }}
          path: './drmem_logs/*'
